import type { Metadata } from "next";
import "./globals.css";
import Header from "./Components/Header";
import { DM_Sans, Old_Standard_TT } from "next/font/google";

const dmsans = DM_Sans({ weight: "variable", subsets: ["latin"] });
const oldstandard = Old_Standard_TT({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Restoran Simpang Raya",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmsans.className} ${oldstandard.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
